---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Кнопка "Добавить в корзину" должна быть легко доступна и видна на всех страницах товара
  - Количество товаров в корзине должно автоматически обновляться без перезагрузки страницы
  - При удалении товара из корзины информация о текущем содержимом корзины должна обновляться, без перезагрузки страницы
  - После оформления заказа пользователь должен получать информацию о статусе
  - Если один и тот же товар добавлен несколько раз в корзину, система должна правильно подсчитать его количество и цену, а не дублировать товар
